# Generated by Django 6.1.1 on 2026-09-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=255)),
                ('tractor_number', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_commodity', models.CharField(max_length=255)),
                ('total_miles_driven', models.PositiveIntegerField(default=0)),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duty_status', models.IntegerField(choices=[(1, 'Off Duty'), (2, 'Sleeper Berth'), (3, 'Driving'), (4, 'On Duty (Not Driving)')])),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logbook.dailylog')),
            ],
        ),
    ]
